import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import Car from "@/components/ui/car";
import { ToastContainer } from "react-toastify";

const ibmPlexSans = Manrope({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rider Secure Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} antialiased`}>
        <div className="min-h-screen bg-gray-100">
          <nav className="bg-white shadow p-4 fixed top-0 left-0 right-0 z-50">
            <h1 className="text-xl tracking-tight font-bold flex items-center justify-between">
              <Link href="/" className="flex items-center gap-2">
                <Car size={32} /> Rider Secure Club
              </Link>
            </h1>
          </nav>
          <ToastContainer position="bottom-right" pauseOnHover={false} />
          <main className="container mx-auto px-4 pb-4 pt-22">{children}</main>
        </div>
      </body>
    </html>
  );
}
