import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import { Plus } from "lucide-react";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rider Secure Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} antialiased`}>
        <div className="min-h-screen bg-gray-200">
          <nav className="bg-white shadow p-4 fixed top-0 left-0 right-0">
            <h1 className="text-2xl font-bold">
              <a href="/">Rider Secure Club</a>
            </h1>
          </nav>
          <main className="container mx-auto px-4 pb-4 pt-22">{children}</main>
        </div>
        <Link
          title="Create new payment"
          href={"/policies"}
          className="fixed bottom-10 right-10 size-12 bg-black text-white rounded-full flex items-center justify-center font-bold shadow-xl transition-all hover:scale-105 active:scale-95"
        >
          <Plus />
        </Link>
      </body>
    </html>
  );
}
